[package]
name = "silky-letter-insa"
version = "{{VERSION}}"
entrypoint = "letter-template.typ"
authors = ["SkytAsul"]
license = "MIT"
description = "A template made for letters and short documents of INSA, a French engineering school."
repository = "https://github.com/SkytAsul/INSA-Typst-Template"
keywords = ["insa", "school", "engineering", "letter"]
disciplines = ["engineering", "computer-science", "mathematics", "physics"]
categories = ["office"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
